---
#
# v1.1.0    2018-03-10    webdev@highskillz.com
#
# must be run with context on the root project folder (prob ../ from this file).
# all paths here are relative to that location
#
# https://docs.docker.com/compose/compose-file/compose-versioning/
# v2:  https://docs.docker.com/compose/compose-file/compose-file-v2/
# v3:  https://docs.docker.com/compose/compose-file/
#
# http://yaml-multiline.info
#
#
version: "2.1"  # latest version supporting extends

# ==============================================================
x--00--build-py3:
    &x--00--build-py3
    context: .
    dockerfile: ./php7x-py3ansible.docker
    # args:
    #     []

services:

# ==============================================================
  # ------------------------------------------------------------
  php70-cli-1604-py3ans:
    image: ez123/php7x:7.0-cli-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.0-cli-1604"

  php71-cli-1604-py3ans:
    image: ez123/php7x:7.1-cli-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.1-cli-1604"

  php72-cli-1604-py3ans:
    image: ez123/php7x:7.2-cli-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.2-cli-1604"

  # ------------------------------------------------------------
  php70-apache-1604-py3ans:
    image: ez123/php7x:7.0-apache-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.0-apache-1604"

  php71-apache-1604-py3ans:
    image: ez123/php7x:7.1-apache-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.1-apache-1604"

  php72-apache-1604-py3ans:
    image: ez123/php7x:7.2-apache-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.2-apache-1604"

  # ------------------------------------------------------------
  php70-fpm-1604-py3ans:
    image: ez123/php7x:7.0-fpm-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.0-fpm-1604"

  php71-fpm-1604-py3ans:
    image: ez123/php7x:7.1-fpm-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.1-fpm-1604"

  php72-fpm-1604-py3ans:
    image: ez123/php7x:7.2-fpm-1604-py3ans
    build:
      << : *x--00--build-py3
      args:
          IMG_BASE_NAME: "ez123/php7x"
          IMG_BASE_TAG: "7.2-fpm-1604"


